pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Unit Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Code Analysis') {
            steps {
                script {
                sh 'sudo /home/vagrant/sonar-runner/sonar-scanner-4.2.0.1873-linux/bin/sonar-scanner -Dsonar.host.url=http://10.174.0.183:9000 -Dsonar.projectKey=web_app -Dsonar.java.binaries=target/classes'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Nexus') {
        steps {
            script {
                def pom = readMavenPom file: 'pom.xml'
                echo pom.version

                nexusArtifactUploader(
                        nexusVersion: 'nexus2',
                        protocol: 'http',
                        nexusUrl: '192.168.0.1:8081/nexus',
                        groupId: 'java-grp',
                        version: "${pom.version}",
                        repository: 'java-repo',
                        credentialsId: 'nexus_cred',
                        artifacts: [
                            [artifactId: 'java_jar',
                            file: 'target/my-app-1.0-SNAPSHOT.jar',
                            type: 'jar']
                        ]
                )
            }
        }
    }
    }
}
